### ISSUE TITLE
Example (create-react-app) is not runing on machine

### ISSUE THREAD

**Issue by mdalishanali** [datalayer/jupyter-react#40] opened 2022-12-06 10:24 UTC
I clone this repo and try to run create-react-app example. When I start the server then I throw the error called module not found of codemirror. 
I had clone twice and thrice to fix this issue. But does not resolve yet. 
Can you try it on your machine. Let me know If is working on your machine.
Thank you!

**Comment by echarles** [comment] 2022-12-15 07:21
Thank you so much @mdalishanali for trying out and reporting. Not sure the cause of the error you have reported. We are living with latest alpha jupyterlab artifacts, so something it can break... In the meantime I have pushed more changes. Would you have time to retry with the following snippet (the Makefile has a fix for a jupyterlab package, so you really need to use it, also please use conda to make sure all the tools are available with the correct version). Thx again!

```
git clone https://github.com/datalayer/jupyter-react.git && \
  cd jupyter-react
conda deactivate && \
  make env-rm # If you want to reset your environment.
make env && \
  conda activate jupyter-react
make install build
yarn start:create-react-app      # open http://localhost:3000
```

**Comment by echarles** [comment] 2022-12-15 16:04
PS: The conda env is now name `datalayer`, so you will have to use `conda activate datalayer`.

**Comment by mdalishanali** [comment] 2022-12-16 03:19
Thank you @echarles

**Comment by echarles** [comment] 2023-01-29 08:45
Closing. Please reopen if you still have issues. Thx.

**Closed by echarles** 2023-01-29 08:45 UTC
Labels: bug
